# Generated by Django 6.0.4 on 2026-04-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_evaluatorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterion',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='criterion',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
