# Generated by Django 6.0.4 on 2026-05-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_educationallevel_grade_school_alter_axis_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluatorprofile',
            name='max_projects',
            field=models.IntegerField(default=100),
        ),
    ]
